//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtiFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppUsers()
        {
            this.Intermediates = new HashSet<Intermediates>();
        }
    
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public int StatusFK { get; set; }
        public bool Admin { get; set; }
        public bool Suspended { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intermediates> Intermediates { get; set; }
    }
}
