//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtiFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artifact()
        {
            this.Intermediates = new HashSet<Intermediates>();
        }
    
        public int ArtifactSK { get; set; }
        public string ArtifactName { get; set; }
        public string ShortDescrition { get; set; }
        public int PeriodBegin { get; set; }
        public int PeriodEnd { get; set; }
        public int CountryFK { get; set; }
        public string PlaceOfOrigin { get; set; }
        public string Link { get; set; }
        public Nullable<int> MuseumFK { get; set; }
        public bool Approved { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Museum Museum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intermediates> Intermediates { get; set; }
    }
}
