//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtiFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intermediates
    {
        public string UserFK { get; set; }
        public int ArtifactFK { get; set; }
        public bool IsUploader { get; set; }
    
        public virtual AppUsers AppUsers { get; set; }
        public virtual Artifact Artifact { get; set; }
    }
}
